---

# Middleware Chains for Traefik

http:
  middlewares:
    weak-web-protect:
      chain:
        middlewares:
          - rate-limit@file
          - in-flight-req@file
          - geoblock@file

    web-protect:
      chain:
        middlewares:
          - weak-web-protect@file
          - crowdsec-bouncer@file
          - fail2ban@file

    websecure-protect:
      chain:
        middlewares:
          - web-protect@file
          - security-headers@file

    weak-websecure-protect:
      chain:
        middlewares:
          - weak-web-protect@file
          - security-headers@file
